query charactersByEpisode($episode: String!) {
	episodes(filter: { episode: $episode }) {
		results {
			characters {
				id
				name
				gender
				species
				episode {
					id
					episode
				}
				image
			}
		}
	}
}
