query Characters($page: Int!, $name: String!) {
	characters(page: $page, filter: { name: $name }) {
		info {
			pages
		}
		results {
			gender
			species
			episode {
				id
				episode
			}
			id
			name
			image
		}
	}
}
